### ISSUE TITLE
Relation fail on _deduceName from Class

### ISSUE THREAD

**Issue by aditbisa** [bogus34/bookshelf-schema#3]
I got this files:

**journal.js**

```
var bookshelf = require('../bookshelf'),
    Relations = require('bookshelf-schema/lib/relations'),
    JournalItems = require('./journalItems');

var JournalModel = bookshelf.Model.extend({
  tableName: 'journal'
},{
  schema: [
    Relations.HasMany(JournalItems)
  ]
});

bookshelf.model('Journal', JournalModel);
module.exports = JournalModel;
```

**journalItems.js**

```
var bookshelf = require('../bookshelf'),
    Relations = require('bookshelf-schema/lib/relations');

var JournalItemsModel = bookshelf.Model.extend({
  tableName: 'journal_items'
},{ });

bookshelf.model('Journal', JournalItemsModel);
module.exports = JournalItemsModel;
```

It always fail on `_deduceName`

```
TypeError: Cannot read property '0' of undefined
    at utils.lowerFirst (....\node_modules\bookshelf-schema\lib\utils.js:86:15)
    at BelongsTo.Relation._deduceName (....\node_modules\bookshelf-schema\lib\relations.js:298:14)
    at BelongsTo.Relation (....\node_modules\bookshelf-schema\lib\relations.js:90:22)
    at new BelongsTo (....\node_modules\bookshelf-schema\lib\relations.js:356:37)
    at ....\node_modules\bookshelf-schema\lib\relations.js:352:45
    at Object.BelongsTo (....\node_modules\bookshelf-schema\lib\relations.js:354:9)
    at Object.<anonymous> (....\libs\models\journalItems.js:18:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (....\libs\models\journal.js:7:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (....\scripts\test-model.js:9:15)
    at Module._compile (module.js:409:26)
```

It is success, when:
1. Relation using string `Relations.HasMany('JournalItems')`. But you need lowerFirstCase `.fetch({withRelated: ['journalItems']})` when fetching.
2. Using name `Relations.HasMany(JournalItems, {name: 'JournalItems'})` and the same case when fetching `.fetch({withRelated: ['JournalItems']})`. Fail on using lowerFirstCase when fetching.

I think that's all.

**Comment by bogus34** [comment]
Hello!

Thanks for pointing this.
The problem is that in Javascript functions ( and consequently classes ) may be anonymous. I've add usage of related table name as a base to deduce relation name. And document the process of generation relation name a little.

> Relation using string Relations.HasMany('JournalItems'). But you need lowerFirstCase .fetch({withRelated: ['journalItems']}) when fetching.

That's correct, relation name uses lowercased first letter if name isn't provided explicitly

> Using name Relations.HasMany(JournalItems, {name: 'JournalItems'}) and the same case when fetching .fetch({withRelated: ['JournalItems']}). Fail on using lowerFirstCase when fetching.

Can't reproduce it, maybe fixed.
