### ISSUE TITLE
Can't work with bookshelf plugin

### ISSUE THREAD

**Issue by aditbisa** [bogus34/bookshelf-schema#4]
FYI,

Can't work with bookshelf plugin which extend & replace Model (e.g: virtuals & visibility).

```
TypeError: Journal.query is not a function
    at Object.<anonymous> (....\test-model.js:13:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
```

This plugins looks extensive. But if I can't create other custom plugin which enrich the Model, hence this is a dead-end.

**Comment by bogus34** [comment]
Hi!
Looks like I've pinned this down. 
The problem was caused by Bookshelf extend method which manipulates **proto** instead of copying static methods directly to child class. It brokes CS class inheritance.
